### PR TITLE
Poro des3d

### PR DESCRIPTION
**Pull request by sungho91**
1. Poroelasticity 
2. Pseudo-transient (PT) method
3. General Neumann (stress) boundary conditions
4. Two benchmarks (Terzaghi and Mandel problems) and Jupyter Notebooks for verification
5. Initial stress calculation using the PT loop

### CODE REVIEW

**Comment by echoi** [comment]
@sungho91 I went over all the changes once and most of them look fine.

One thing I noticed is that `has_hydraulic_diffusion` is not found in `parameters.hpp` and `input.[cxx,hpp]`. The parameter is being set to be `true` in the config files in `benchmarks`, though. I don't understand how those benchmarks could run successfully. Anyway, it seems to be a simple fix.

On a separate note, can you attach the PowerPoint file you presented at the last DES3D meeting here or send it to me over Teams?

**Comment by echoi** [comment]
@sungho91 I went over all the changes once and most of them look fine.

One thing I noticed is that `has_hydraulic_diffusion` is not found in `parameters.hpp` and `input.[cxx,hpp]`. The parameter is being set to be `true` in the config files in `benchmarks`, though. I don't understand how those benchmarks could run successfully. Anyway, it seems to be a simple fix.

On a separate note, can you attach the PowerPoint file you presented at the last DES3D meeting here or send it to me over Teams?

**Comment by echoi** [comment]
@sungho91 I went over all the changes once and most of them look fine.

One thing I noticed is that `has_hydraulic_diffusion` is not found in `parameters.hpp` and `input.[cxx,hpp]`. The parameter is being set to be `true` in the config files in `benchmarks`, though. I don't understand how those benchmarks could run successfully. Anyway, it seems to be a simple fix.

On a separate note, can you attach the PowerPoint file you presented at the last DES3D meeting here or send it to me over Teams?

**Comment by echoi** [comment]
@sungho91 I went over all the changes once and most of them look fine.

One thing I noticed is that `has_hydraulic_diffusion` is not found in `parameters.hpp` and `input.[cxx,hpp]`. The parameter is being set to be `true` in the config files in `benchmarks`, though. I don't understand how those benchmarks could run successfully. Anyway, it seems to be a simple fix.

On a separate note, can you attach the PowerPoint file you presented at the last DES3D meeting here or send it to me over Teams?

**Comment by echoi** [comment]
I looked at the web editor that shows conflicts as well as followed the command line instructions.
image
When viewed on the web editor, the data member `has_hydraulic_diffusion` was not a part of the `Control` structure in `parameters.hpp` and was not getting a vlue in `input.cxx`. However, `has_hydraulic_diffusion` was being used in many other parts. The same thing happened when I followed the command line instructions.

Since @sungho91 didn't seem to see this inconsistency, I cloned a clean copy and then checked out the `poro-des3d` branch. This time, `has_hydraulic_diffusion` was in `parameters.hpp` and getting a value assigned in `input.cxx`.
I don't understand what causes this difference and what it implies for the result of merging this pull request. 

However, since the `poro-des3d` branch is working fine by itself, it seems reasonable to merge it and then resolve any issues as they pop up. @tan2, what do you think?

**Comment by tan2** [comment]
I agree with Eunseo to merge it and then resolve the conflict in the master branch.

**Comment by echoi** [comment]
Well, after merging changes in `poro-des3d` branch, all checks have failed because of the errors like
`bc.cxx:1125:35: error: ‘const struct Control’ has no member named ‘has_hydraulic_diffusion’; did you mean ‘has_thermal_diffusion’?`

@sungho91, I think this pull request should include the addition of the data member.

**Comment by sungho91** [comment]
@echoi , I think problem is resolved. I don't know why mmg hasn't been compiled. maybe path issue.

**Review by echoi — APPROVED** [review]
No more issues with this pull request.

**Comment by echoi** [comment]
@tan2, probably not much to review this time but can you please approve the pull request?

**Review by tan2 — APPROVED** [review]
